/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package example.methods.surveyexample.model;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

/**
 * Definition of ObjectType Votes.
 *
 * @since 2021-12-07
 */
@PrimaryKeys({"id"})
public final class Votes extends CloudDBZoneObject {
    private Integer id;

    private Integer yes;

    private Integer no;

    public Votes() {
        super(Votes.class);
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }

    public void setYes(Integer yes) {
        this.yes = yes;
    }

    public Integer getYes() {
        return yes;
    }

    public void setNo(Integer no) {
        this.no = no;
    }

    public Integer getNo() {
        return no;
    }

}
